### ISSUE TITLE
Q: how to distinguish data constructor and function application?

### ISSUE THREAD

**Issue by csabahruska** [bgamari/ghc-dump#15]
Is it possible to tell from an `id` referred by a `Var` if it means a function application or a data constructor application?

**Comment by bgamari** [comment]
This can be determined by looking at the `IdDetails ` attached to the identifier.

**Comment by csabahruska** [comment]
Can a data constructor be an `EVarGlobal`?

**Comment by bgamari** [comment]
Ahh, great point. Yes, indeed it can be. I suppose we could serialise the `IdDetails` for external identifiers as well, although this may be somewhat verbose. May I ask what your use-case is?

**Comment by csabahruska** [comment]
I'm using GHC as a Haskell front-end for a whole program optimizer and code generator. see: [GRIN compiler](https://github.com/grin-tech/grin)

**Comment by bgamari** [comment]
Ahh, of course. Are you using `ghc-dump` to pull core out of GHC?

**Comment by csabahruska** [comment]
Yes, I'm using a modified version of `ghc-dump-core` to save the core expression for each compiled module. My version of `ghc-dump` is using `Binary` and I added it's source to GHC so that it work with the standard tooling like `stack` flawlessly.
https://github.com/grin-tech/grin/tree/master/libs/ghc-dump-core

But that's a minor change only and it does not touch it's design.

**Comment by bgamari** [comment]
I see; I originally designed `ghc-dump` as a debugging tool, to provide a view slightly more structured than the usual `-dverbose-core2core` output. I'm willing to add more detail to the the format if this is useful, but I'd prefer for the files not to grow too much larger than they already are. Perhaps you would like to put together a PR adding `IdDetails` to external names and characterise the effect?

**Comment by csabahruska** [comment]
At the moment the system is in experimental phase. Whenever it stabilizes then I can send a PR.
