### ISSUE TITLE
Include instructions for building binary-serialise-cbor

### ISSUE THREAD

**Issue by treeowl** [bgamari/ghc-dump#7]
```
git submodule init
git submodule update
cabal install ./binary-serialise-cbor/
```
or something like that.

**Comment by bgamari** [comment]
David Feuer <notifications@github.com> writes:

> ```
> git submodule init
> git submodule update
> cabal install ./binary-serialise-cbor/
> ```
> or something like that.
>
I do hope that binary-serialise-cbor will be released Real Soon Now(TM).

**Comment by bgamari** [comment]
It has been released! Yay!
